name: Linting

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/**'
      - 'build/**'
      - '.github/pages/**'
  pull_request:
    branches:
      - main

jobs:
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/gh-pages'  # gh-pages Branch ausschlie√üen, da sonst Fehler auftreten

    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.4

      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm ci

      - name: run Prettier
        run: npm run prettier

      - name: run ESlint
        run: npm run lint 

        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}